#!/usr/bin/env python3
"""Build a self-contained QPKG recognised by QNAP App Center.

The format is documented by QNAP's public QDK. This script intentionally uses
only Python's standard library: QDK is not a runtime dependency of the NAS.
"""
from __future__ import annotations

import hashlib
import os
import re
import shutil
import tarfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "build"
WORK = BUILD / "qpkg-work"


def read_cfg() -> dict[str, str]:
    values: dict[str, str] = {}
    pattern = re.compile(r'^(QPKG_[A-Z0-9_]+)="([^"]*)"\s*$')
    for line in (ROOT / "qpkg.cfg").read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            values[match.group(1)] = match.group(2)
    missing = [key for key in ("QPKG_NAME", "QPKG_VER", "QPKG_ARCH") if not values.get(key)]
    if missing:
        raise SystemExit(f"qpkg.cfg is missing: {', '.join(missing)}")
    return values


def make_tar(output: Path, entries: list[tuple[Path, str]], mode: str, fmt: int) -> None:
    with tarfile.open(output, mode, format=fmt) as archive:
        for source, name in entries:
            archive.add(source, arcname=name, recursive=True)


def qpkg_header(name: str, control_size: int, data_size: int) -> bytes:
    template = f'''#!/bin/sh
# QPKG bootstrap generated by tools/build_qpkg.py
find_base() {{
    QPKG_NAME="{name}"
    if [ -n "${{QINSTALL_PATH:-}}" ] && [ -d "$QINSTALL_PATH" ]; then
        QPKG_INSTALL_PATH="$QINSTALL_PATH"
        return 0
    fi
    publicdir="$(/sbin/getcfg Public path -f /etc/config/smb.conf 2>/dev/null || true)"
    if [ -n "$publicdir" ] && [ -d "$publicdir" ]; then
        QPKG_INSTALL_PATH="$(dirname "$publicdir")/.qpkg"
    else
        for volume in /share/CACHEDEV1_DATA /share/CE_CACHEDEV1_DATA /share/MD0_DATA /share/*_DATA; do
            [ -d "$volume" ] || continue
            QPKG_INSTALL_PATH="$volume/.qpkg"
            break
        done
    fi
    [ -n "${{QPKG_INSTALL_PATH:-}}" ] || return 1
}}
[ "$(/bin/uname -m)" = "x86_64" ] || {{ echo "This package requires x86_64." >&2; exit 1; }}
find_base || {{ echo "No QNAP data volume found." >&2; exit 1; }}
_EXTRACT_DIR="$QPKG_INSTALL_PATH/.tmp-{name}"
/bin/mkdir -p "$_EXTRACT_DIR" || exit 1
script_len=SCRIPT_LEN
/bin/dd if="${{0}}" bs=$script_len skip=1 2>/dev/null | /bin/tar -xO 2>/dev/null | /bin/tar -xz -C "$_EXTRACT_DIR" || exit 1
offset=$(expr $script_len + {control_size})
/bin/dd if="${{0}}" bs=$offset skip=1 2>/dev/null | /bin/dd of="$_EXTRACT_DIR/data.tar.gz" bs=1 count={data_size} 2>/dev/null || exit 1
( cd "$_EXTRACT_DIR" && /bin/sh ./qinstall.sh )
result=$?
/bin/rm -rf "$_EXTRACT_DIR"
# QTS/App Center treats exit status 10 as a successful, completed QPKG
# installation (and may remove the uploaded installer). A plain zero is
# interpreted as an interrupted install even when qinstall.sh succeeded.
[ "$result" -eq 0 ] && exit 10
exit $result
exit 1
'''
    length = len(template.replace("SCRIPT_LEN", "0").encode())
    while True:
        candidate = template.replace("SCRIPT_LEN", str(length)).encode()
        if len(candidate) == length:
            return candidate
        length = len(candidate)


def binary_tail(name: str, version: str, total_size: int) -> bytes:
    if len(name.encode()) > 20 or len(version.encode()) > 10:
        raise SystemExit("QPKG name must fit 20 bytes and version must fit 10 bytes")
    tail = bytearray(
        b" " * 10 + b" " * 40 + b" " * 10 +
        name.encode().ljust(20, b" ") + version.encode().ljust(10, b" ") + b"QNAPQPKG  "
    )
    tail[40:50] = str(total_size * 3589 + 1_000_000_000).encode()[:10].ljust(10, b"0")
    return bytes(tail)


def main() -> None:
    cfg = read_cfg()
    name, version, arch = cfg["QPKG_NAME"], cfg["QPKG_VER"], cfg["QPKG_ARCH"]
    output = BUILD / f"{name}_{version}_{arch}.qpkg"
    shutil.rmtree(WORK, ignore_errors=True)
    (WORK / "control").mkdir(parents=True)
    data = WORK / "data"
    data.mkdir()
    for relative in ("qpkg.cfg", "installer.sh", "shared", "config", "icons", "assets", "runtime", "webui", "THIRD_PARTY_NOTICES.md"):
        source, target = ROOT / relative, data / relative
        if source.is_dir():
            shutil.copytree(source, target)
        else:
            shutil.copy2(source, target)
    (data / "installer.sh").chmod(0o755)
    (data / "shared" / cfg["QPKG_SERVICE_PROGRAM"]).chmod(0o755)
    data_archive = WORK / "data.tar.gz"
    make_tar(data_archive, [(item, item.name) for item in data.iterdir()], "w:gz", tarfile.PAX_FORMAT)

    control = WORK / "control"
    shutil.copy2(ROOT / "qinstall.sh", control / "qinstall.sh")
    (control / "qinstall.sh").chmod(0o755)
    shutil.copy2(ROOT / "qpkg.cfg", control / "qpkg.cfg")
    (control / "package_routines").write_text("# Reserved for QTS package hooks.\n", encoding="utf-8")
    (control / "built_info").write_text(f"time = {datetime.now(timezone.utc):%Y%m%d}\n", encoding="ascii")
    control_gz = WORK / "control.tar.gz"
    make_tar(control_gz, [(item, item.name) for item in control.iterdir()], "w:gz", tarfile.PAX_FORMAT)
    control_tar = WORK / "control.tar"
    make_tar(control_tar, [(control_gz, "control.tar.gz")], "w", tarfile.GNU_FORMAT)

    header = qpkg_header(name, control_tar.stat().st_size, data_archive.stat().st_size)
    content = header + control_tar.read_bytes() + data_archive.read_bytes()
    output.parent.mkdir(exist_ok=True)
    output.write_bytes(content + binary_tail(name, version, len(content) + 100))
    os.chmod(output, 0o644)
    (BUILD / f"{output.name}.md5").write_text(
        f"{hashlib.md5(output.read_bytes()).hexdigest()}  {output.name}\n", encoding="ascii"
    )
    print(f"Built: {output}")
    print("Upload this file in App Center → Install Manually. No QDK is needed on the NAS.")


if __name__ == "__main__":
    main()
